### ISSUE TITLE
TagListView 1.1.0 Swift 3.0 EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by gsujathap** [ElaWorkshop/TagListView#82] opened 2016-11-02 13:04 UTC
while adding tags to the taglistview I am gettiing exc_bad_access error. How to resolve this one.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38884085-taglistview-1-1-0-swift-3-0-exc_bad_access?utm_campaign=plugin&utm_content=tracker%2F16419772&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F16419772&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by Cee** [comment] 2016-11-03 11:07
Could you provide your code snippet?

**Comment by gsujathap** [comment] 2016-11-03 11:09
![screen shot 2016-11-03 at 4 38 34 pm](https://cloud.githubusercontent.com/assets/16931145/19963795/0abe72b0-a1e4-11e6-8a23-f68f5afed544.png)

**Comment by Cee** [comment] 2016-11-04 07:25
@gsujathap Could you reproduce this bug? And if possible, please provide us with more details. (You can tick the checkbox labeled [**Enable Zombie Objects**](https://code.tutsplus.com/tutorials/what-is-exc_bad_access-and-how-to-debug-it--cms-24544).)

**Comment by gsujathap** [comment] 2016-11-04 07:44
![screen shot 2016-11-04 at 1 12 58 pm](https://cloud.githubusercontent.com/assets/16931145/19998065/900395ac-a290-11e6-8ac1-d7daccf05385.png)

**Comment by gsujathap** [comment] 2016-11-04 07:55
In the above screen "PSKILLSET" is the taglistview and I am trying to add tags to the pskillset. please find out the bug

**Comment by aleene** [comment] 2016-11-06 14:16
It might be that your pSkillSet is still nil when you do addTag. Add a check to be certain (pSkillSet != nil).
It might help to do the reloading in viewWillAppear() to make sure pSkillSet is defined.

**Comment by gsujathap** [comment] 2016-11-07 05:29
@aleene whatever you said I have tried in the same way but, still I am getting same error please look at the below screen
![screen shot 2016-11-07 at 10 54 40 am](https://cloud.githubusercontent.com/assets/16931145/20047325/28cb8336-a4d9-11e6-82bc-dfaaa4a718b3.png)

**Comment by Cee** [comment] 2016-11-07 05:35
@gsujathap so would you like to try enabling Enable Zombie Objects as I mentioned above?

**Comment by gsujathap** [comment] 2016-11-07 05:50
I don't know how to approach in Xcode 8 version to 

> Enable Zombie Objects

.

**Comment by gsujathap** [comment] 2016-11-07 06:31
I have enabled Zombie Objects still I didn't resolve this issue. While running Xcode after successful enabling zombie objects It didn't show any message.

**Comment by gsujathap** [comment] 2016-11-07 06:32
@Cee 
I have enabled Zombie Objects still I didn't resolve this issue. While running Xcode after successful enabling zombie objects It didn't show any message.

**Comment by gsujathap** [comment] 2016-11-07 07:17
@Cee 
when i have enabled Zombie Objects   also i am not able to resolve this issue.But while running Xcode after enable Zombie Objects then it is not showing any mesage

**Comment by gsujathap** [comment] 2016-11-07 11:33
pSkillSet.delegate = self
 also shows same error exc_bad_access please provide me correct solution

**Comment by gsujathap** [comment] 2016-11-07 11:34
@aleene  pSkillSet.delegate = self
also shows same error exc_bad_access please provide me correct solution

**Comment by aleene** [comment] 2016-11-07 14:41
I can only think of wrong hookup in the Storyboard that gives this kind of error.

What  does the error-console of Xcode say?

**Comment by gsujathap** [comment] 2016-11-07 14:59
Showing nothing

**Comment by aleene** [comment] 2016-11-07 15:41
![screen shot 2016-11-07 at 16 39 46](https://cloud.githubusercontent.com/assets/1329905/20063817/d8374330-a508-11e6-97d2-ad67a8d057b8.png)
Did you set the View as a custom class in the Storyboard?

**Comment by gsujathap** [comment] 2016-11-07 16:14
Yes

**Comment by aleene** [comment] 2016-11-07 16:41
I ran out of ideas then.

**Comment by Cee** [comment] 2016-11-08 02:33
EXC_BAD_ACCESS (code: 2) means that you're using your `pSkillSet` outlet after calling it's `dealloc` method. Carefully check your storyboards and codes.

**Comment by aleene** [comment] 2016-11-08 10:11
Easiest is to restart with a fresh viewController and add only the tagViewer code. If that works add the json-stuff without the multithreading.

**Comment by gsujathap** [comment] 2016-11-11 05:21
This bug has not been resolved with your answers

**Comment by aquarhead** [comment] 2016-11-11 10:09
Hello @gsujathap I'd suggest you move this question to https://stackoverflow.com/ and tag with Swift, this seems to be a general code error and not a particular issue with TagListView itself.

StackOverflow usually have people with better overall knowledge of Swift and might provide more useful suggestions on `EXC_BAD_ACCESS` errors.

Closing for now as it seems nobody here has better ideas to solve your problem.

**Closed by aquarhead** 2016-11-11 10:09 UTC
Labels: question

**Comment by gsujathap** [comment] 2016-11-11 10:22
How can you close this issue without solving. Actually I used this library in swift2.2 at that time It works smoothly but, In swift3.0 its not working. this bug is not because of general code error. How can it works in swift2.2 previously?

**Comment by gsujathap** [comment] 2016-11-11 10:22
@aquarhead How can you close this issue without solving. Actually I used this library in swift2.2 at that time It works smoothly but, In swift3.0 its not working. this bug is not because of general code error. How can it works in swift2.2 previously?

**Comment by xhacker** [comment] 2016-11-11 10:26
@gsujathap: Please provide a minimal project that has this error if you really want this to be resolved.

**Comment by Cee** [comment] 2016-11-11 10:26
Sorry @gsujathap, we couldn't reproduce this error again.

If you really need help, push your whole project to GitHub and then give us the link.

**Comment by aquarhead** [comment] 2016-11-11 10:26
I have stated why, and suggested how you could have better luck finding a solution.

StackOverflow would also help you better understand problems occurred with the Swift 2 -> 3 transition.

**Comment by gsujathap** [comment] 2016-11-11 10:35
@aquarhead Thank you for your immediate reply. Finally it is solved 👍

**Comment by aleene** [comment] 2016-11-11 11:18
Could you tell how you solved it? Might be useful for others.

**Comment by gsujathap** [comment] 2016-11-11 11:22
![screen shot 2016-11-11 at 4 51 14 pm](https://cloud.githubusercontent.com/assets/16931145/20213522/16b31368-a82f-11e6-85ad-e3ce20868f80.png)
not only setting custom class but also we have to set module
